--- 
title: "Analysis workflow for IMC data"
author: "**Authors:** Nils Eling [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS)<sup>,</sup>[<sup>*</sup>](#email), Vito Zanotelli [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS), Michelle Daniel [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS), Daniel Schulz [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS), Jonas Windhager [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS), Lasse Meyer [<sup>1</sup>](#DQBM)<sup>,</sup>[<sup>2</sup>](#IMHS)"
date: "**Compiled:** `r Sys.Date()`"
site: bookdown::bookdown_site
github-repo: "BodenmillerGroup/IMCDataAnalysis"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This bookdown project highlights possible down-stream analyses performed on imaging mass cytometry data."
---

# IMC Data Analysis Workflow {#preamble}

This workflow highlights the use of common R/Bioconductor packages
to analyze single-cell data obtained from segmented multi-channel images. We will not perform multi-channel image processing and segmentation in R
but rather link to available approaches in Section \@ref(processing). While we
use imaging mass zytometry (IMC) data as an example, the concepts presented here can be applied to images
obtained by other highly-multiplexed imaging technologies (e.g. CODEX, MIBI,
mIF, etc.).

We will give an introduction to IMC in Section \@ref(intro) and highlight
strategies to extract single-cell data from multi-channel images in Section
\@ref(processing).

Reproducible code written in R is available from Section \@ref(prerequisites)
onwards and the workflow can be largely divided into the following parts:

1. Preprocessing (reading in the data, spillover correction)
2. Image- and cell-level quality control, low-dimensional visualization
3. Sample/batch effect correction
4. Cell phenotyping via clustering or classification
5. Single-cell and image visualization
6. Spatial analyses

## Disclaimer

Multi-channel image and spatial, single-cell analysis is complex and we
highlight an example workflow here. However, this workflow is not complete and
does not cover all possible aspects of exploratory data analysis. Instead, we
demonstrate this workflow as a solid basis that supports other aspects of data
analysis. It offers interoperability with other packages for single-cell and
spatial analysis and the user will need to become familiar with the general
framework to efficiently analyse data obtained from multiplexed imaging
technologies.

## Feedback and contributing

We provide the workflow as an open-source resource. It does not mean that
this workflow is tested on all possible datasets or biological questions.

If you notice an issue or missing information, please report an issue
[here](https://github.com/BodenmillerGroup/IMCDataAnalysis/issues). We also
welcome contributions in form of pull requests or feature requests in form of
issues. Have a look at the source code at:

[https://github.com/BodenmillerGroup/IMCDataAnalysis](https://github.com/BodenmillerGroup/IMCDataAnalysis)

## Citation

The workflow is currently under development for final publication.
In the meantime please refer to the 
[preprint](https://www.biorxiv.org/content/10.1101/2021.11.12.468357v1) 
which you can site as follows:

```
Jonas Windhager, Bernd Bodenmiller, Nils Eling (2020). An end-to-end workflow for multiplexed image processing and analysis. 
    bioRxiv, doi: 10.1101/2021.11.12.468357
```

---

<a name="email"><sup>*</sup></a> nils.eling@uzh.ch  
<a name="DQBM">1:</a> Department for Quantitative Biomedicine, University of Zurich  
<a name="IMHS">2:</a> Institute for Molecular Health Sciences, ETH Zurich  
