on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: build

jobs:
  bookdown:
    runs-on: ubuntu-latest
    container: rocker/r-ver:latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install CRAN dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "tidyverse", "pheatmap", "viridis", "zoo", "BiocManager"))'
      - name: Install Bioconductor dependencies
        run: Rscript -e 'BiocManager::install("CATALYST")'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         name: _book # optional
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          BUILD_DIR: _book/                     # "_site/" by default
    
 
