on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 5'

name: build

jobs:
  bookdown:
    runs-on: ubuntu-latest
    container: ghcr.io/bodenmillergroup/imcdataanalysis:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check Dockerfile change
        shell: pwsh
        id: check_dockerfile_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if the Dockerfile has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match 'Dockerfile' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "dockerfile_changed"
          Write-Host "::set-output name=dockerfile_changed::$HasDiff"
      
      - name: Render Book conditional 1
        if: steps.check_dockerfile_changed.outputs.dockerfile_changed == 'True'
        uses: lewagon/wait-on-check-action@v1.0.0
        with: 
          ref: ${{ github.ref }}
          check-name: 'Build and Push Docker Image'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          
      - name: Render Book conditional 2
        run: Rscript -e 'bookdown::render_book("index.Rmd", new_session = TRUE)'
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/
  
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs # optional
          path: docs # optional
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          force_orphan: true
    
 
