on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 5'

name: build

jobs:
  bookdown:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install system requirements
        run: |
          apt-get update 
          apt-get install -y --no-install-recommends apt-utils 
          apt-get install -y --no-install-recommends zlib1g-dev libfftw3-dev libxml2-dev libxt-dev curl libcairo2-dev libproj-dev libgdal-dev libudunits2-dev
          apt-get clean
          rm -rf /var/lib/apt/ilists/*
          
      - name: Install CRAN dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "pheatmap", "viridis", 
                                            "zoo", "BiocManager", "devtools", "testthat", "tiff",
                                            "distill", "openxlsx", "ggrepel", "patchwork", "mclust",
                                            "RColorBrewer"))'
      - name: Install Bioconductor dependencies
        run: Rscript -e 'BiocManager::install(c("CATALYST", "scuttle", "scater", "dittoSeq", "tidyverse", "BiocStyle"))'
      - name: Install Github dependencies
        run: Rscript -e 'devtools::install_github(c("BodenmillerGroup/imcRtools", "BodenmillerGroup/cytomapper"))'    
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         name: docs # optional
         path: docs # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v2
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          BUILD_DIR: docs/                     # "_site/" by default
    
 
