on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 1 * *'

name: docker_deploy

jobs:
  build-push:
    name: Buid and push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      env:
        REGISTRY: ghcr.io
        OWNER: BodenmillerGroup
        IMAGE_NAME: ${{ github.repository }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        target: final
        push: true
        tags: |
          $REGISTRY/$OWNER/$IMAGE_NAME:$(date +'%Y-%m-%d'),$REGISTRY/$OWNER/$IMAGE_NAME:latest
        build-args: |
          ENVIRONMENT=production