on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 1 * *'

name: docker_deploy

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract steinbock metadata
        id: steinbock_meta
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
      
      - name: set NOW
        id: now
        run: |
            echo "::set-output name=NOW::$(date +'%Y-%m-%d')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nilseling/imc_analysis:${{ steps.now.outputs.NOW }},nilseling/imc_analysis:latest